# Generated by Django 3.2.5 on 2021-07-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(null=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
